"""email

Revision ID: 97791de9ee48
Revises: 
Create Date: 2025-08-27 12:04:04.477187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97791de9ee48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
